[package]
name = "app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ui = { path = "../ui" }
tg = { path = "../tg" }
grammers-client = { git = "https://github.com/Lonami/grammers" }
grammers-session = { git = "https://github.com/Lonami/grammers" }
tokio = { version = "1", features = ["rt", "macros", "sync", "net", "time", "io-util", "fs"] }
anyhow = "1"
mimalloc.workspace = true