[package]
name = "ui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
winit.workspace = true
softbuffer.workspace = true
tiny-skia.workspace = true
fontdue = "0.8"
tokio = { version = "1", features = ["sync"] }
chrono = { version = "0.4", default-features = false, features = ["clock", "std", "alloc"] }
jpeg-decoder = "0.3"
arboard = "3.4"

[lib]
name = "ui"
path = "src/lib.rs"